### ISSUE TITLE
Checklist dos Boladões

### ISSUE THREAD

**Issue by thlmenezes** [alinevitoriasi/boladao-web#7]
# Critérios de aceitação

Esse problema será criado nos projetos [boladão web#7](https://github.com/alinevitoriasi/boladao-web/issues/7) e [boladão T3#1](https://github.com/thlmenezes/boladao-t3/issues/1) para garantir que ambos projetos cumprem os requisitos funcionais e que colaboradores externos possam acompanhar o progresso do projeto e do _remake_.

Ao serem completadas, ambos irão apresentar os projetos finalizados e conversar sobre a experiência, não se esquecendo de mencionar os aspectos:

- Aprendizado
- DX (experiência de desenvolvimento, do inglês _developer experience_)
  - Padrões de Projeto (ESLint, Prettier, ...)
- Velocidade: quantas horas de live trabalhadas no projeto?
- Responsividade
- Acessibilidade

## Básico

- [x] início
- [x] criar conta
- [x] login
- [x] criar post
- [x] listar todos os posts
- [ ] na lista de posts, um post deve conter: conteúdo, foto do usuário, nome do usuário e botão copiar para área de transferência
- [x] listar meus posts
- [x] editar post
- [x] excluir post
- [ ] o botão de copiar para área de transferência deve conter o texto do post com o sufixo "Copiado de projeto boladão <3"*

## Avançado

- [ ] as listas de posts devem estar paginadas: explicitamente (1,2,3,...) ou lista infinita (feed do Instagram)
- [ ] as listas de posts devem estar ordenadas com os posts mais recentes primeiro (opcionalmente mostrando a data de publicação)
- [ ] escolher se os posts aparecem publicamente ou não (públicos ou privados)
- [ ] selecionar instituição ao criar post
- [ ] uma instituição possui um nome e uma localização (CEP ou latitude e longitude)**
- [ ] copiar para área de transferência passa a incluir nome e link do google maps da instituição
- [ ] tags com categorias para posts, conforme o tipo de relato (deverá ser disponibilizada lista com tags)
- [ ] filtrar lista de posts por categoria

*[função de copiar para área de transferência](https://github.com/thlmenezes/boladao-t3/blob/9b7b1262c794853fe2b35d32387bc14a48a056d7/src/pages/posts/index.tsx#L11)
**caso escolha latitude e longitude fica a recomendação da biblioteca [leafletjs](https://leafletjs.com/) e o link do google pode ser montado `https://www.google.com/maps/@${latitude},${longitude},15z`
